#!/usr/bin/env python3

import argparse
import sys
import hid
import time
import re

def parse_frequency(freq_str):
    """Parse frequency string into Hz."""
    freq_str = freq_str.lower().strip()
    
    # Check for kHz suffix
    if freq_str.endswith('khz') or freq_str.endswith('k'):
        freq = float(freq_str[:-3] if freq_str.endswith('khz') else freq_str[:-1])
        return int(freq * 1000)
    
    # Check for MHz suffix
    elif freq_str.endswith('mhz') or freq_str.endswith('m'):
        freq = float(freq_str[:-3] if freq_str.endswith('mhz') else freq_str[:-1])
        return int(freq * 1000000)
    
    # Assume Hz if no suffix
    else:
        return int(float(freq_str))

def send_command(device, command):
    """Send a command to the RigExpert Match device."""
    data_list = [7, len(command)] + [ord(c) for c in command] + [0] * 65
    device.write(bytes(data_list[:64]))

def read_response(device):
    """Read a response from the RigExpert Match device."""
    data = device.read(64)
    if data:
        data_len = data[1]
        response = ''.join(chr(b) for b in data[2:data_len + 2])
        return response
    return None

def _open_device():
    """Open RigExpert Match device using available hid API."""
    DeviceCls = getattr(hid, "Device", None)
    if DeviceCls is not None:
        return DeviceCls(0x0483, 0xa1de)
    dev = hid.device()
    dev.open(0x0483, 0xa1de)
    return dev


def check_connection():
    """Check if the RigExpert Match device is connected."""
    try:
        device = _open_device()
        device.close()
        return True
    except Exception:
        return False


def get_device():
    """Get a handle to the RigExpert Match device."""
    try:
        return _open_device()
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def status_command():
    """Display the connection status of the RigExpert Match device."""
    if check_connection():
        print("RigExpert Match is connected.")
        sys.exit(0)
    else:
        print("RigExpert Match is not connected.", file=sys.stderr)
        sys.exit(1)

def read_data_command(center_freq, sweep_range, num_points, trace=False, output_path=None):
    """Read R and X values from the RigExpert Match device."""
    device = None
    output_file = None
    try:
        if output_path:
            output_file = open(output_path, "w", encoding="utf-8")
        device = get_device()
        
        # Set frequency
        freq_cmd = f"FQ{center_freq}\r"
        if trace:
            print(f"Command sent: {freq_cmd.strip()}")
        send_command(device, freq_cmd)
        time.sleep(0.1)
        # Read response after setting frequency
        data = read_response(device)
        if trace:
            print(f"Response after FQ: {data}")
        
        # Set sweep range
        sw_cmd = f"SW{sweep_range}\r"
        if trace:
            print(f"Command sent: {sw_cmd.strip()}")
        send_command(device, sw_cmd)
        time.sleep(0.1)
        # Read response after setting sweep range
        data = read_response(device)
        if trace:
            print(f"Response after SW: {data}")
        
        # Start sweep and read data
        frx_cmd = f"FRX{num_points}\r"
        if trace:
            print(f"Command sent: {frx_cmd.strip()}")
        send_command(device, frx_cmd)
        time.sleep(0.1)
        # Read response after starting sweep
        data = read_response(device)
        if trace:
            print(f"Response after FRX: {data}")
        
        from datetime import datetime
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        def write_line(line):
            if output_file:
                output_file.write(line + "\n")
            else:
                print(line)

        write_line(f"! Touchstone file generated by match-cli.py on {timestamp}")
        write_line("# MHz Z RI R 50")
        
        data_points = []
        while len(data_points) < num_points:
            data = read_response(device)
            if trace:
                print(f"Raw data: {data}")
            if data and "OK" in data:
                # Extract R and X values
                match = re.search(r'([-+]?\d+\.?\d*),([-+]?\d+\.?\d*),([-+]?\d+\.?\d*)', data)
                if match:
                    freq_value = match.group(1)
                    r_value = match.group(2)
                    x_value = match.group(3)
                    data_points.append((freq_value, r_value, x_value))
                    # Use the actual frequency from the data
                    write_line(f"{freq_value} {r_value} {x_value}")
            elif data and "," in data:
                # Handle alternative data format
                parts = data.strip().split(",")
                if len(parts) >= 3:
                    freq_value = parts[0]
                    r_value = parts[1]
                    x_value = parts[2]
                    data_points.append((freq_value, r_value, x_value))
                    # Use the actual frequency from the data
                    write_line(f"{freq_value} {r_value} {x_value}")
            elif not data:
                # No more data to read
                break
        
        if len(data_points) != num_points:
            print(f"Warning: Expected {num_points} data points, but received {len(data_points)}", file=sys.stderr)
    
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(3)
    
    finally:
        if device:
            device.close()
        if output_file:
            output_file.close()

def main():
    parser = argparse.ArgumentParser(
        description="Control the RigExpert Match Antenna Analyzer.",
        epilog="Example: python3 match-cli.py read --center 100MHz --range 200MHz --points 100"
    )
    
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    
    # Status command
    status_parser = subparsers.add_parser('status', help='Check connection status')
    status_parser.set_defaults(func=status_command)
    
    # Read data command
    read_parser = subparsers.add_parser(
        'read',
        help='Read R and X values',
        description='Read R and X values from the RigExpert Match device.',
        epilog='Example: python3 match-cli.py read --center 100MHz --range 200MHz --points 100'
    )
    read_parser.add_argument(
        '--center',
        type=str,
        default='100MHz',
        help='Center frequency (e.g., 100MHz, 100m, 100kHz, 100k)'
    )
    read_parser.add_argument(
        '--range',
        type=str,
        default='200MHz',
        help='Sweep range (e.g., 200MHz, 200m, 200kHz, 200k)'
    )
    read_parser.add_argument(
        '--points',
        type=int,
        default=100,
        help='Number of points to read'
    )
    read_parser.add_argument(
        '--trace',
        action='store_true',
        help='Enable trace mode to output raw data from the analyzer'
    )
    read_parser.add_argument(
        '-o',
        '--output',
        type=str,
        help='Write Touchstone output to a file instead of stdout'
    )
    read_parser.set_defaults(func=read_data_command)
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        sys.exit(0)
    
    if args.command == 'read':
        # Parse frequency arguments
        center_freq = parse_frequency(args.center)
        sweep_range = parse_frequency(args.range)
        # Execute the read command
        read_data_command(center_freq, sweep_range, args.points, args.trace, args.output)
    else:
        args.func()

if __name__ == '__main__':
    main()
